2022-05-14 10:45:20,900 - celery.beat - INFO - Scheduler: Sending due task Twitter Scrapping (scrapper.tasks.scrape_twitter)
2022-05-14 10:45:20,916 - celery.worker.strategy - INFO - Task scrapper.tasks.scrape_twitter[e825abe1-68fb-4adc-ae29-3126fe8d02b7] received
2022-05-14 10:45:22,144 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 10:45:22,144 - scrapper.tasks - INFO - 2022-05-14 02:53:09+00:00
2022-05-14 10:45:22,144 - scrapper.tasks - INFO - <class 'datetime.datetime'>
2022-05-14 10:45:22,144 - scrapper.tasks - INFO - <class 'str'>
2022-05-14 10:45:22,144 - scrapper.tasks - INFO - 20220514-025309
2022-05-14 10:45:22,146 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 10:45:22,146 - scrapper.tasks - INFO - 2022-05-14 02:52:36+00:00
2022-05-14 10:45:22,146 - scrapper.tasks - INFO - <class 'datetime.datetime'>
2022-05-14 10:45:22,146 - scrapper.tasks - INFO - <class 'str'>
2022-05-14 10:45:22,146 - scrapper.tasks - INFO - 20220514-025236
2022-05-14 10:45:22,147 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 10:45:22,147 - scrapper.tasks - INFO - 2022-05-14 02:52:08+00:00
2022-05-14 10:45:22,147 - scrapper.tasks - INFO - <class 'datetime.datetime'>
2022-05-14 10:45:22,147 - scrapper.tasks - INFO - <class 'str'>
2022-05-14 10:45:22,147 - scrapper.tasks - INFO - 20220514-025208
2022-05-14 10:45:22,149 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 10:45:22,149 - scrapper.tasks - INFO - 2022-05-14 02:48:38+00:00
2022-05-14 10:45:22,149 - scrapper.tasks - INFO - <class 'datetime.datetime'>
2022-05-14 10:45:22,149 - scrapper.tasks - INFO - <class 'str'>
2022-05-14 10:45:22,149 - scrapper.tasks - INFO - 20220514-024838
2022-05-14 10:45:22,150 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 10:45:22,150 - scrapper.tasks - INFO - 2022-05-14 02:47:50+00:00
2022-05-14 10:45:22,150 - scrapper.tasks - INFO - <class 'datetime.datetime'>
2022-05-14 10:45:22,151 - scrapper.tasks - INFO - <class 'str'>
2022-05-14 10:45:22,151 - scrapper.tasks - INFO - 20220514-024750
2022-05-14 10:45:22,158 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 10:45:22,158 - scrapper.tasks - INFO - 2022-05-13 23:47:38+00:00
2022-05-14 10:45:22,158 - scrapper.tasks - INFO - <class 'datetime.datetime'>
2022-05-14 10:45:22,158 - scrapper.tasks - INFO - <class 'str'>
2022-05-14 10:45:22,158 - scrapper.tasks - INFO - 20220513-234738
2022-05-14 10:45:22,161 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 10:45:22,162 - scrapper.tasks - INFO - 2022-05-13 21:06:15+00:00
2022-05-14 10:45:22,162 - scrapper.tasks - INFO - <class 'datetime.datetime'>
2022-05-14 10:45:22,162 - scrapper.tasks - INFO - <class 'str'>
2022-05-14 10:45:22,162 - scrapper.tasks - INFO - 20220513-210615
2022-05-14 10:45:22,168 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 10:45:22,168 - scrapper.tasks - INFO - 2022-05-13 20:16:48+00:00
2022-05-14 10:45:22,168 - scrapper.tasks - INFO - <class 'datetime.datetime'>
2022-05-14 10:45:22,168 - scrapper.tasks - INFO - <class 'str'>
2022-05-14 10:45:22,168 - scrapper.tasks - INFO - 20220513-201648
2022-05-14 10:45:22,178 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 10:45:22,178 - scrapper.tasks - INFO - 2022-05-13 18:01:09+00:00
2022-05-14 10:45:22,179 - scrapper.tasks - INFO - <class 'datetime.datetime'>
2022-05-14 10:45:22,179 - scrapper.tasks - INFO - <class 'str'>
2022-05-14 10:45:22,179 - scrapper.tasks - INFO - 20220513-180109
2022-05-14 10:45:22,186 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 10:45:22,187 - scrapper.tasks - INFO - 2022-05-13 16:31:18+00:00
2022-05-14 10:45:22,187 - scrapper.tasks - INFO - <class 'datetime.datetime'>
2022-05-14 10:45:22,187 - scrapper.tasks - INFO - <class 'str'>
2022-05-14 10:45:22,187 - scrapper.tasks - INFO - 20220513-163118
2022-05-14 10:45:22,189 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 10:45:22,189 - scrapper.tasks - INFO - 2022-05-13 16:20:49+00:00
2022-05-14 10:45:22,189 - scrapper.tasks - INFO - <class 'datetime.datetime'>
2022-05-14 10:45:22,189 - scrapper.tasks - INFO - <class 'str'>
2022-05-14 10:45:22,189 - scrapper.tasks - INFO - 20220513-162049
2022-05-14 10:45:22,218 - celery.app.trace - INFO - Task scrapper.tasks.scrape_twitter[e825abe1-68fb-4adc-ae29-3126fe8d02b7] succeeded in 1.3010347979979997s: None
2022-05-14 11:00:20,904 - celery.beat - INFO - Scheduler: Sending due task Twitter Scrapping (scrapper.tasks.scrape_twitter)
2022-05-14 11:00:20,907 - celery.worker.strategy - INFO - Task scrapper.tasks.scrape_twitter[525c1067-ee88-4541-864f-4034f28f0a93] received
2022-05-14 11:00:21,727 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 11:00:21,727 - scrapper.tasks - INFO - 2022-05-14 10:55:11+00:00
2022-05-14 11:00:21,728 - scrapper.tasks - INFO - <class 'datetime.datetime'>
2022-05-14 11:00:21,728 - scrapper.tasks - INFO - <class 'str'>
2022-05-14 11:00:21,728 - scrapper.tasks - INFO - 20220514-105511
2022-05-14 11:00:21,743 - celery.app.trace - ERROR - Task scrapper.tasks.scrape_twitter[525c1067-ee88-4541-864f-4034f28f0a93] raised unexpected: ValidationError(['“20220514-105511” value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format.'])
Traceback (most recent call last):
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/scrapper/tasks.py", line 62, in scrape_twitter
    Article.objects.create(title=title, link=link, pub_date=pub_date, source=source, external_id=external_id)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1415, in execute_sql
    for sql, params in self.as_sql():
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1358, in as_sql
    value_rows = [
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1300, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 842, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1427, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1406, in get_prep_value
    value = super().get_prep_value(value)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1266, in get_prep_value
    return self.to_python(value)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1388, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“20220514-105511” value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format.']
2022-05-14 11:15:20,912 - celery.beat - INFO - Scheduler: Sending due task Twitter Scrapping (scrapper.tasks.scrape_twitter)
2022-05-14 11:15:20,914 - celery.worker.strategy - INFO - Task scrapper.tasks.scrape_twitter[b17fd41d-0cd6-4fee-a98d-5b69e1bd0326] received
2022-05-14 11:15:21,741 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 11:15:21,741 - scrapper.tasks - INFO - 2022-05-14 10:55:11+00:00
2022-05-14 11:15:21,741 - scrapper.tasks - INFO - <class 'datetime.datetime'>
2022-05-14 11:15:21,741 - scrapper.tasks - INFO - <class 'str'>
2022-05-14 11:15:21,742 - scrapper.tasks - INFO - 20220514-105511
2022-05-14 11:15:21,745 - celery.app.trace - ERROR - Task scrapper.tasks.scrape_twitter[b17fd41d-0cd6-4fee-a98d-5b69e1bd0326] raised unexpected: ValidationError(['“20220514-105511” value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format.'])
Traceback (most recent call last):
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/scrapper/tasks.py", line 62, in scrape_twitter
    Article.objects.create(title=title, link=link, pub_date=pub_date, source=source, external_id=external_id)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1415, in execute_sql
    for sql, params in self.as_sql():
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1358, in as_sql
    value_rows = [
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1300, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 842, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1427, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1406, in get_prep_value
    value = super().get_prep_value(value)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1266, in get_prep_value
    return self.to_python(value)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1388, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“20220514-105511” value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format.']
2022-05-14 11:30:20,919 - celery.beat - INFO - Scheduler: Sending due task Twitter Scrapping (scrapper.tasks.scrape_twitter)
2022-05-14 11:30:20,921 - celery.worker.strategy - INFO - Task scrapper.tasks.scrape_twitter[a8e31acd-fabd-4240-98b8-fd0ea6372d03] received
2022-05-14 11:30:21,765 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 11:30:21,765 - scrapper.tasks - INFO - 2022-05-14 10:55:11+00:00
2022-05-14 11:30:21,765 - scrapper.tasks - INFO - <class 'datetime.datetime'>
2022-05-14 11:30:21,765 - scrapper.tasks - INFO - <class 'str'>
2022-05-14 11:30:21,765 - scrapper.tasks - INFO - 20220514-105511
2022-05-14 11:30:21,772 - celery.app.trace - ERROR - Task scrapper.tasks.scrape_twitter[a8e31acd-fabd-4240-98b8-fd0ea6372d03] raised unexpected: ValidationError(['“20220514-105511” value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format.'])
Traceback (most recent call last):
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/scrapper/tasks.py", line 62, in scrape_twitter
    Article.objects.create(title=title, link=link, pub_date=pub_date, source=source, external_id=external_id)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1415, in execute_sql
    for sql, params in self.as_sql():
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1358, in as_sql
    value_rows = [
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1300, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 842, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1427, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1406, in get_prep_value
    value = super().get_prep_value(value)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1266, in get_prep_value
    return self.to_python(value)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1388, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“20220514-105511” value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format.']
2022-05-14 11:44:25,559 - celery.beat - INFO - beat: Starting...
2022-05-14 11:44:29,751 - celery.redirected - WARNING - Exception ignored in atexit callback
2022-05-14 11:44:29,751 - celery.redirected - WARNING - : 
2022-05-14 11:44:29,751 - celery.redirected - WARNING - <function _exit_function at 0x7f45a0622d40>
2022-05-14 11:44:29,751 - celery.redirected - WARNING - Traceback (most recent call last):
2022-05-14 11:44:29,751 - celery.redirected - WARNING -   File "/usr/lib/python3.10/multiprocessing/util.py", line 334, in _exit_function
2022-05-14 11:44:29,754 - celery.redirected - WARNING -     
2022-05-14 11:44:29,754 - celery.redirected - WARNING - _run_finalizers(0)
2022-05-14 11:44:29,755 - celery.redirected - WARNING -   File "/usr/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
2022-05-14 11:44:29,755 - celery.redirected - WARNING -     
2022-05-14 11:44:29,755 - celery.redirected - WARNING - finalizer()
2022-05-14 11:44:29,755 - celery.redirected - WARNING -   File "/usr/lib/python3.10/multiprocessing/util.py", line 224, in __call__
2022-05-14 11:44:29,756 - celery.redirected - WARNING -     
2022-05-14 11:44:29,756 - celery.redirected - WARNING - res = self._callback(*self._args, **self._kwargs)
2022-05-14 11:44:29,756 - celery.redirected - WARNING -   File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/billiard/pool.py", line 1662, in _terminate_pool
2022-05-14 11:44:29,757 - celery.redirected - WARNING -     
2022-05-14 11:44:29,758 - celery.redirected - WARNING - cls._help_stuff_finish(*help_stuff_finish_args)
2022-05-14 11:44:29,758 - celery.redirected - WARNING -   File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 1341, in _help_stuff_finish
2022-05-14 11:44:29,759 - celery.redirected - WARNING -     
2022-05-14 11:44:29,759 - celery.redirected - WARNING - readable, _, again = _select(inqR, timeout=0.5)
2022-05-14 11:44:29,759 - celery.redirected - WARNING -   File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 165, in _select
2022-05-14 11:44:29,760 - celery.redirected - WARNING -     
2022-05-14 11:44:29,760 - celery.redirected - WARNING - return poll(readers, writers, err, timeout)
2022-05-14 11:44:29,760 - celery.redirected - WARNING -   File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 121, in _select_imp
2022-05-14 11:44:29,760 - celery.redirected - WARNING -     
2022-05-14 11:44:29,761 - celery.redirected - WARNING - events = poller.poll(timeout)
2022-05-14 11:44:29,761 - celery.redirected - WARNING -   File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/apps/worker.py", line 299, in _handle_request
2022-05-14 11:44:29,761 - celery.redirected - WARNING -     
2022-05-14 11:44:29,762 - celery.redirected - WARNING - raise exc(exitcode)
2022-05-14 11:44:29,762 - celery.redirected - WARNING - celery.exceptions
2022-05-14 11:44:29,762 - celery.redirected - WARNING - .
2022-05-14 11:44:29,762 - celery.redirected - WARNING - WorkerTerminate
2022-05-14 11:44:29,762 - celery.redirected - WARNING - : 
2022-05-14 11:44:29,763 - celery.redirected - WARNING - 1
2022-05-14 11:44:31,843 - kombu.connection - WARNING - No hostname was supplied. Reverting to default 'localhost'
2022-05-14 11:44:32,393 - celery.worker.consumer.connection - INFO - Connected to amqp://guest:**@127.0.0.1:5672//
2022-05-14 11:44:32,396 - celery.worker.consumer.mingle - INFO - mingle: searching for neighbors
2022-05-14 11:44:32,401 - kombu.connection - WARNING - No hostname was supplied. Reverting to default 'localhost'
2022-05-14 11:44:33,413 - celery.worker.consumer.mingle - INFO - mingle: all alone
2022-05-14 11:44:33,438 - py.warnings - WARNING - /home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

2022-05-14 11:44:33,438 - celery.apps.worker - INFO - celery@ebirdmax-HVY-WXX9 ready.
2022-05-14 11:44:35,042 - celery.worker.control - INFO - Events of group {task} enabled by remote.
2022-05-14 12:15:20,941 - celery.beat - INFO - Scheduler: Sending due task Twitter Scrapping (scrapper.tasks.scrape_twitter)
2022-05-14 12:15:20,946 - celery.worker.strategy - INFO - Task scrapper.tasks.scrape_twitter[3129b05b-30dc-48c0-a557-d72d1e7eb634] received
2022-05-14 12:15:21,754 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:15:21,754 - scrapper.tasks - INFO - 2022-05-14 12:15:10+00:00
2022-05-14 12:15:21,754 - scrapper.tasks - INFO - <class 'datetime.datetime'>
2022-05-14 12:15:21,754 - scrapper.tasks - INFO - <class 'float'>
2022-05-14 12:15:21,754 - scrapper.tasks - INFO - 1652530510.0
2022-05-14 12:15:21,757 - celery.app.trace - ERROR - Task scrapper.tasks.scrape_twitter[3129b05b-30dc-48c0-a557-d72d1e7eb634] raised unexpected: TypeError('expected string or bytes-like object')
Traceback (most recent call last):
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/scrapper/tasks.py", line 62, in scrape_twitter
    cache.set('last_id', last_id)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1415, in execute_sql
    for sql, params in self.as_sql():
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1358, in as_sql
    value_rows = [
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1300, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 842, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1427, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1406, in get_prep_value
    value = super().get_prep_value(value)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1266, in get_prep_value
    return self.to_python(value)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1367, in to_python
    parsed = parse_datetime(value)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/utils/dateparse.py", line 107, in parse_datetime
    match = datetime_re.match(value)
TypeError: expected string or bytes-like object
2022-05-14 12:17:57,522 - kombu.connection - WARNING - No hostname was supplied. Reverting to default 'localhost'
2022-05-14 12:17:58,032 - celery.worker.consumer.connection - INFO - Connected to amqp://guest:**@127.0.0.1:5672//
2022-05-14 12:17:58,038 - celery.worker.consumer.mingle - INFO - mingle: searching for neighbors
2022-05-14 12:17:58,044 - kombu.connection - WARNING - No hostname was supplied. Reverting to default 'localhost'
2022-05-14 12:17:59,055 - celery.worker.consumer.mingle - INFO - mingle: all alone
2022-05-14 12:17:59,075 - py.warnings - WARNING - /home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

2022-05-14 12:17:59,075 - celery.apps.worker - INFO - celery@ebirdmax-HVY-WXX9 ready.
2022-05-14 12:18:16,642 - celery.worker.control - INFO - Events of group {task} enabled by remote.
2022-05-14 12:18:26,059 - celery.beat - INFO - beat: Starting...
2022-05-14 12:18:26,144 - celery.beat - INFO - Scheduler: Sending due task Twitter Scrapping (scrapper.tasks.scrape_twitter)
2022-05-14 12:18:26,152 - celery.worker.strategy - INFO - Task scrapper.tasks.scrape_twitter[613a0ca2-8ac2-4a53-a9e9-a6503c8222b4] received
2022-05-14 12:18:26,962 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:26,966 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:26,975 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:26,981 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:26,987 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:26,993 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:26,999 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,005 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,011 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,020 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,026 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,032 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,038 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,044 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,050 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,052 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,055 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,083 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,086 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,089 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,094 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,097 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,117 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,125 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,141 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,168 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,188 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,193 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:18:27,251 - celery.app.trace - INFO - Task scrapper.tasks.scrape_twitter[613a0ca2-8ac2-4a53-a9e9-a6503c8222b4] succeeded in 1.0985599829982675s: None
2022-05-14 12:33:26,149 - celery.beat - INFO - Scheduler: Sending due task Twitter Scrapping (scrapper.tasks.scrape_twitter)
2022-05-14 12:33:26,152 - celery.worker.strategy - INFO - Task scrapper.tasks.scrape_twitter[9396cc43-b163-46c4-88c8-3b70451351c3] received
2022-05-14 12:33:27,054 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:33:27,067 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:33:27,069 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:33:27,095 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:33:27,097 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:33:27,099 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:33:27,104 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:33:27,107 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:33:27,127 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:33:27,134 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:33:27,149 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:33:27,183 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:33:27,208 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:33:27,214 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:33:27,269 - celery.app.trace - INFO - Task scrapper.tasks.scrape_twitter[9396cc43-b163-46c4-88c8-3b70451351c3] succeeded in 1.1157525369999348s: None
2022-05-14 12:37:40,583 - kombu.connection - WARNING - No hostname was supplied. Reverting to default 'localhost'
2022-05-14 12:37:41,124 - celery.worker.consumer.connection - INFO - Connected to amqp://guest:**@127.0.0.1:5672//
2022-05-14 12:37:41,127 - celery.worker.consumer.mingle - INFO - mingle: searching for neighbors
2022-05-14 12:37:41,131 - kombu.connection - WARNING - No hostname was supplied. Reverting to default 'localhost'
2022-05-14 12:37:42,140 - celery.worker.consumer.mingle - INFO - mingle: all alone
2022-05-14 12:37:42,153 - py.warnings - WARNING - /home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

2022-05-14 12:37:42,153 - celery.apps.worker - INFO - celery@ebirdmax-HVY-WXX9 ready.
2022-05-14 12:37:55,496 - celery.worker.control - INFO - Events of group {task} enabled by remote.
2022-05-14 12:38:01,602 - celery.beat - INFO - beat: Starting...
2022-05-14 12:48:26,166 - celery.beat - INFO - Scheduler: Sending due task Twitter Scrapping (scrapper.tasks.scrape_twitter)
2022-05-14 12:48:26,181 - celery.worker.strategy - INFO - Task scrapper.tasks.scrape_twitter[2018d1cb-6584-4ae3-a313-d46a0bf44ed0] received
2022-05-14 12:48:27,068 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 12:48:27,068 - scrapper.tasks - INFO - 2022-05-14 12:48:07+00:00
2022-05-14 12:48:27,068 - scrapper.tasks - INFO - <class 'datetime.datetime'>
2022-05-14 12:48:27,068 - scrapper.tasks - INFO - YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]
2022-05-14 12:48:27,068 - scrapper.tasks - INFO - <class 'str'>
2022-05-14 12:48:27,082 - celery.app.trace - ERROR - Task scrapper.tasks.scrape_twitter[2018d1cb-6584-4ae3-a313-d46a0bf44ed0] raised unexpected: ValidationError(['“YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]” value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format.'])
Traceback (most recent call last):
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/scrapper/tasks.py", line 62, in scrape_twitter
    Article.objects.create(title=title, link=link, pub_date=pub_date, source=source, external_id=external_id)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1415, in execute_sql
    for sql, params in self.as_sql():
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1358, in as_sql
    value_rows = [
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1300, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 842, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1427, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1406, in get_prep_value
    value = super().get_prep_value(value)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1266, in get_prep_value
    return self.to_python(value)
  File "/home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1388, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]” value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format.']
2022-05-14 12:57:17,676 - kombu.connection - WARNING - No hostname was supplied. Reverting to default 'localhost'
2022-05-14 12:57:18,242 - celery.worker.consumer.connection - INFO - Connected to amqp://guest:**@127.0.0.1:5672//
2022-05-14 12:57:18,245 - celery.worker.consumer.mingle - INFO - mingle: searching for neighbors
2022-05-14 12:57:18,249 - kombu.connection - WARNING - No hostname was supplied. Reverting to default 'localhost'
2022-05-14 12:57:19,259 - celery.worker.consumer.mingle - INFO - mingle: all alone
2022-05-14 12:57:19,269 - py.warnings - WARNING - /home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

2022-05-14 12:57:19,269 - celery.apps.worker - INFO - celery@ebirdmax-HVY-WXX9 ready.
2022-05-14 12:57:28,245 - celery.worker.control - INFO - Events of group {task} enabled by remote.
2022-05-14 12:57:29,701 - celery.beat - INFO - beat: Starting...
2022-05-14 13:03:26,167 - celery.beat - INFO - Scheduler: Sending due task Twitter Scrapping (scrapper.tasks.scrape_twitter)
2022-05-14 13:03:26,184 - celery.worker.strategy - INFO - Task scrapper.tasks.scrape_twitter[64b5fa29-ef82-4729-84d3-95aeedfe86c2] received
2022-05-14 13:03:27,079 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:03:27,090 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:03:27,096 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:03:27,114 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:03:27,117 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:03:27,144 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:03:27,147 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:03:27,150 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:03:27,155 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:03:27,158 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:03:27,180 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:03:27,188 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:03:27,203 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:03:27,225 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:03:27,232 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:03:27,234 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:03:27,257 - celery.app.trace - INFO - Task scrapper.tasks.scrape_twitter[64b5fa29-ef82-4729-84d3-95aeedfe86c2] succeeded in 1.071642716997303s: None
2022-05-14 13:18:26,172 - celery.beat - INFO - Scheduler: Sending due task Twitter Scrapping (scrapper.tasks.scrape_twitter)
2022-05-14 13:18:26,175 - celery.worker.strategy - INFO - Task scrapper.tasks.scrape_twitter[beb66de2-5b4a-4bd7-b5d0-585f22b5a482] received
2022-05-14 13:18:27,063 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:18:27,070 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:18:27,072 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:18:27,083 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:18:27,084 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:18:27,085 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:18:27,087 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:18:27,089 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:18:27,096 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:18:27,099 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:18:27,105 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:18:27,117 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:18:27,124 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:18:27,127 - scrapper.tasks - INFO - !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2022-05-14 13:18:27,150 - celery.app.trace - INFO - Task scrapper.tasks.scrape_twitter[beb66de2-5b4a-4bd7-b5d0-585f22b5a482] succeeded in 0.9730412339995382s: None
2022-05-15 06:03:29,186 - kombu.connection - WARNING - No hostname was supplied. Reverting to default 'localhost'
2022-05-15 06:03:29,708 - celery.worker.consumer.connection - INFO - Connected to amqp://guest:**@127.0.0.1:5672//
2022-05-15 06:03:29,712 - celery.worker.consumer.mingle - INFO - mingle: searching for neighbors
2022-05-15 06:03:29,726 - kombu.connection - WARNING - No hostname was supplied. Reverting to default 'localhost'
2022-05-15 06:03:30,739 - celery.worker.consumer.mingle - INFO - mingle: all alone
2022-05-15 06:03:30,759 - py.warnings - WARNING - /home/ebirdmax/Documents/Programmieren/researchbrowserproject-1/venv/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

2022-05-15 06:03:30,760 - celery.apps.worker - INFO - celery@ebirdmax-HVY-WXX9 ready.
2022-05-15 06:03:59,089 - celery.worker.control - INFO - Events of group {task} enabled by remote.
2022-05-15 06:04:19,529 - celery.beat - INFO - beat: Starting...
2022-05-15 06:04:19,604 - celery.beat - INFO - Scheduler: Sending due task Twitter Scrapping (scrapper.tasks.scrape_twitter)
2022-05-15 06:04:19,611 - celery.worker.strategy - INFO - Task scrapper.tasks.scrape_twitter[b0250a80-79f4-48cc-aaf8-cf5a0a1b7b39] received
2022-05-15 06:04:21,027 - celery.app.trace - INFO - Task scrapper.tasks.scrape_twitter[b0250a80-79f4-48cc-aaf8-cf5a0a1b7b39] succeeded in 1.4147976009999752s: None
2022-05-15 06:19:19,609 - celery.beat - INFO - Scheduler: Sending due task Twitter Scrapping (scrapper.tasks.scrape_twitter)
2022-05-15 06:19:19,612 - celery.worker.strategy - INFO - Task scrapper.tasks.scrape_twitter[b5aaa484-0757-451e-8eb2-f668e4abfe79] received
2022-05-15 06:19:20,640 - celery.app.trace - INFO - Task scrapper.tasks.scrape_twitter[b5aaa484-0757-451e-8eb2-f668e4abfe79] succeeded in 1.026817458000096s: None
2022-05-15 06:34:19,613 - celery.beat - INFO - Scheduler: Sending due task Twitter Scrapping (scrapper.tasks.scrape_twitter)
2022-05-15 06:34:19,615 - celery.worker.strategy - INFO - Task scrapper.tasks.scrape_twitter[5a4ea00a-7644-411f-a97f-a6c3a3a5d34f] received
2022-05-15 06:34:21,305 - celery.app.trace - INFO - Task scrapper.tasks.scrape_twitter[5a4ea00a-7644-411f-a97f-a6c3a3a5d34f] succeeded in 1.6879922109997096s: None
2022-05-15 06:49:19,621 - celery.beat - INFO - Scheduler: Sending due task Twitter Scrapping (scrapper.tasks.scrape_twitter)
2022-05-15 06:49:19,624 - celery.worker.strategy - INFO - Task scrapper.tasks.scrape_twitter[8e3455f8-3e65-420b-ba98-43a8ff8c3f4e] received
2022-05-15 06:49:20,681 - celery.app.trace - INFO - Task scrapper.tasks.scrape_twitter[8e3455f8-3e65-420b-ba98-43a8ff8c3f4e] succeeded in 1.0558503859997472s: None
2022-05-15 07:04:19,629 - celery.beat - INFO - Scheduler: Sending due task Twitter Scrapping (scrapper.tasks.scrape_twitter)
2022-05-15 07:04:19,631 - celery.worker.strategy - INFO - Task scrapper.tasks.scrape_twitter[d0ba55dc-b767-4567-bfaf-134e1dbd5345] received
2022-05-15 07:04:20,602 - celery.app.trace - INFO - Task scrapper.tasks.scrape_twitter[d0ba55dc-b767-4567-bfaf-134e1dbd5345] succeeded in 0.9688271340000938s: None
2022-05-15 07:19:19,636 - celery.beat - INFO - Scheduler: Sending due task Twitter Scrapping (scrapper.tasks.scrape_twitter)
2022-05-15 07:19:19,639 - celery.worker.strategy - INFO - Task scrapper.tasks.scrape_twitter[3196b0cf-b592-4237-9b36-1eb040b79125] received
2022-05-15 07:19:20,583 - celery.app.trace - INFO - Task scrapper.tasks.scrape_twitter[3196b0cf-b592-4237-9b36-1eb040b79125] succeeded in 0.9425648280002861s: None
